name: Add new issues to Org Project

on:
  issues:
    types: [opened, reopened, edited]

jobs:
  add_issue_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to UTM v1 project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Zoppingg/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
